facts :
  about : Wholesale fruit sales to stores
  name : sales
  date_scale : day
  quantity_low : 1
  quantity_high : 30
dimensions :
- fruit
  unit : pound
  value : dollar
- stores
  unit : sale
  value : quantity
- store_size
  
